package edu.cnm.deepdive.mealornomeal.model.entity;

import edu.cnm.deepdive.mealornomeal.view.FlatListItem;
import java.net.URI;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * The ListItem Entity class lists methods for the attributes of the Ingredient.
 * These include: Id, Name, and Quantity. The Ingredient populates the Meal Entity as to the food
 * items included as part of the meal. They also serve as the building blocks for ingredients for
 * ListItems for the shopping list feature.
 */
@SuppressWarnings("JpaDataSourceORMInspection")
@Entity
public class ListItem implements FlatListItem {

  /**
   * The column Id in the database that contains the Primary Key for a specific List Item in
   * type Long. This Id is autogenerated, cannot be null, and cannot be updated.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "list_item_id", nullable = false, updatable = false)
  private Long id;

  /**
   * The column Name in the database that contains the name for a specific ListItem in
   * String format. The max String length is 100 characters and it cannot be null.
   */
  @Column(name = "name", length = 100, nullable = false)
  private String name;

  /**
   * The column Name in the database that contains the Quantity for a specific ListItem in
   * String format. The max String length is 50 characters and it cannot be null.
   */
  @Column(name = "quantity", length = 50, nullable = false)
  private String quantity;

  /**
   * The column User Id in the database that contains the Id of a specific User. This is a foreign
   * key in the ListItem Entity and is used to join the List Item and User Id. It has a
   * Many-to-One relationship with User.
   */
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "user_id")
  private User user_id;

  public void setName(String name) {
    this.name = name;
  }

  public void setQuantity(String quantity) {
    this.quantity = quantity;
  }

  public void setUser_id(User user_id) {
    this.user_id = user_id;
  }

  public Long getId() {
    return id;
  }

  @Override
  public String getListItem() {
    return null;
  }

  @Override
  public URI getHref() {
    return null;
  }

  public String getName() {
    return name;
  }

  public String getQuantity() {
    return quantity;
  }

  public User getUser_id() {
    return user_id;
  }
}


