package edu.cnm.deepdive.mealornomeal.controller;

import edu.cnm.deepdive.mealornomeal.exception.AccessDeniedException;
import edu.cnm.deepdive.mealornomeal.model.entity.Ingredient;
import edu.cnm.deepdive.mealornomeal.model.entity.Meal;
import edu.cnm.deepdive.mealornomeal.model.service.IngredientRepository;
import edu.cnm.deepdive.mealornomeal.model.service.MealRepository;
import edu.cnm.deepdive.mealornomeal.model.service.UserService;
import java.util.NoSuchElementException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.hateoas.server.ExposesResourceFor;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

/**
 * The MealController controls the details of a Meal entity when it is created or modified. It also
 * allows a User to search for meals, edit meals they have created, and delete meals.
 */

@RestController
@RequestMapping("/meals")
@ExposesResourceFor(Meal.class)
public class MealController {

  private final MealRepository mealRepository;
  private final IngredientRepository ingredientRepository;
  private final UserService userService;

  /**
   * A consturctor that creates contextualized instances of the Meal and User repositories.
   *
   * @param -                    Takes a mealRepository parameter
   * @param -                    Takes a userRepository parameter
   * @param ingredientRepository
   * @param userService
   */
  @Autowired
  public MealController(MealRepository mealRepository,
      IngredientRepository ingredientRepository,
      UserService userService) {
    this.mealRepository = mealRepository;
    this.ingredientRepository = ingredientRepository;
    this.userService = userService;
  }

  /**
   * Allows the user to get a specific Meal entity with a specific ID.
   *
   * @param id - the Meal's Primary Key and identifier
   * @return - returns the Meal with the specified ID
   * @throws - throws a NoSuchElementException if there is no existing Meal with the provided ID
   */
  @GetMapping(value = "/{id:\\d+}", produces = MediaType.APPLICATION_JSON_VALUE)
  public Meal get(@PathVariable Long id, Authentication auth) {
    return mealRepository.findById(id).orElseThrow(NoSuchElementException::new);
  }

  /**
   * Allows the user to get a list of Meals sorted by the ID of the user who created them.
   */
  @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
  public Iterable<Meal> getMeals(Authentication auth) {
    return mealRepository.getAllByOrderByName();
  }


  /**
   * Allows the user to search for meals with names that contain a specified String. It returns all
   * matching meals in ascending alphabetical order.
   *
   * @param filter - A String input provided by the user.
   * @return - All meals with names that contain the String filter.
   */
  @GetMapping(value = "/search", produces = MediaType.APPLICATION_JSON_VALUE)
  public Iterable<Meal> search(@RequestParam(name = "q", required = true) String filter,
      Authentication auth) {
    return mealRepository.getAllByNameContainingOrderByNameAsc(filter);
  }

  /**
   * Allows the user to POST a Meal entity and assigns the user's ID as the creator ID associated
   * with that meal.
   *
   * @param meal - A meal entity containing at minimum a name, an autogenerated ID, and an
   *             instruction attribute.
   * @return - Returns a response from the server that the Meal has been created and shows the
   * created meal.
   */
  @PostMapping(
      consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
  public ResponseEntity<Meal> postMeal(@RequestBody Meal meal, Authentication auth) {
    return userService.get(auth)
        .map((user) -> {
          meal.setCreator(user);
          mealRepository.save(meal);
          return ResponseEntity.created(meal.getHref()).body(meal);
        })
        .orElseThrow(AccessDeniedException::new);
  }
  /**
   * Allows the user to edit the name of a meal they have created.
   *
   * @param id   - ID associated with the specific meal
   * @param name - The body of the Meal entity containing the Name attribute the user is editing
   * @return - Returns the current Meal entity with the newly updated Name
   */
  @PutMapping(value = "/{id:\\d+}/meal-name",
      consumes = {MediaType.APPLICATION_JSON_VALUE,
          MediaType.TEXT_PLAIN_VALUE}, produces = MediaType.APPLICATION_JSON_VALUE)
  public Meal putName(@PathVariable Long id, @RequestBody String name, Authentication auth) {
    Meal existingMeal = get(id, auth);
    existingMeal.setName(name);
    return mealRepository.save(existingMeal);
  }

  /**
   * Allows the user to edit the instruction of a meal they have created.
   *
   * @param id     - ID associated with the specific meal
   * @param recipe - The body of the Meal entity containing the Instruction attribute the user is
   *               editing
   * @return - Returns the current Meal entity with the newly updated Instruction
   */
  @PutMapping(value = "/{id:\\d+}/instruction",
      consumes = {MediaType.APPLICATION_JSON_VALUE,
          MediaType.TEXT_PLAIN_VALUE}, produces = MediaType.APPLICATION_JSON_VALUE)
  public Meal putInstruction(@PathVariable Long id, @RequestBody String recipe,
      Authentication auth) {
    Meal existingMeal = get(id, auth);
    existingMeal.setInstruction(recipe);
    return mealRepository.save(existingMeal);
  }

  /**
   * Allows the user to edit the prep time of a meal they have created.
   *
   * @param id       - ID associated with the specific meal
   * @param prepTime - The body of the Meal entity containing the PrepTime attribute the user is
   *                 editing
   * @return - Returns the current Meal entity with the newly updated PrepTime
   */

  @PutMapping(value = "/{id:\\d+}/prep",
      consumes = {MediaType.APPLICATION_JSON_VALUE,
          MediaType.TEXT_PLAIN_VALUE}, produces = MediaType.APPLICATION_JSON_VALUE)
  public Meal putPrepTime(@PathVariable Long id, @RequestBody int prepTime, Authentication auth) {
    Meal existingMeal = get(id, auth);
    existingMeal.setPrepTime(prepTime);
    return mealRepository.save(existingMeal);
  }

  /**
   * Allows the user to edit the requirement of a meal they have created.
   *
   * @param id           - ID associated with the specific meal
   * @param requirements - The body of the Meal entity containing the Requirement attribute the user
   *                     is editing
   * @return - Returns the current Meal entity with the newly updated Requirement
   */

  @PutMapping(value = "/{id:\\d+}/requirements",
      consumes = {MediaType.APPLICATION_JSON_VALUE,
          MediaType.TEXT_PLAIN_VALUE}, produces = MediaType.APPLICATION_JSON_VALUE)
  public Meal putRequirements(@PathVariable Long id, @RequestBody String requirements,
      Authentication auth) {
    Meal existingMeal = get(id, auth);
    existingMeal.setRequirements(requirements);
    return mealRepository.save(existingMeal);
  }

  @PostMapping(value = "/{id:\\d+}/ingredients",
      consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
  public ResponseEntity<Ingredient> postIngredient(@PathVariable Long id,
      @RequestBody Ingredient ingredient,
      Authentication auth) {
    return userService.get(auth)
        .flatMap((user) ->
            mealRepository.findById(id)
                .map((meal) -> {
                  userService.requireAccess(user, meal.getCreator());
                  return meal;
                })
        )
        .map((meal) -> {
          ingredient.setMeal(meal);
          ingredientRepository.save(ingredient);
          return ResponseEntity.created(ingredient.getHref()).body(ingredient);
        })
        .orElseThrow(NoSuchElementException::new);
  }

  @GetMapping(value = "/{id:\\d+}/ingredients", produces = MediaType.APPLICATION_JSON_VALUE)
  public Iterable<Ingredient> getIngredients(@PathVariable Long id, Authentication auth) {
    return mealRepository.findById(id)
        .map((meal) -> meal.getIngredients())
        .orElseThrow(NoSuchElementException::new);
  }

  @PutMapping(value = "/{id:\\d+}/ingredients/{ingredientId:\\d+}",
      consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
  public Ingredient putIngredient(@PathVariable Long id, @PathVariable long ingredientId,
      @RequestBody Ingredient ingredient, Authentication auth) {
    return userService.get(auth)
        .flatMap((user) ->
            mealRepository.findById(id)
                .map((meal) -> {
                  userService.requireAccess(user, meal.getCreator());
                  return meal;
                })
        )
        .flatMap((meal) ->
            ingredientRepository.findById(ingredientId)
                .map((existing) -> {
                  if (ingredient.getName() != null) {
                    existing.setName(ingredient.getName());
                  }
                  if (ingredient.getQuantity() != null) {
                    existing.setQuantity(ingredient.getQuantity());
                  }
                  return ingredientRepository.save(existing);
                })
        )
        .orElseThrow(NoSuchElementException::new);
  }

  @DeleteMapping(value = "/{id:\\d+}/ingredients/{ingredientId:\\d+}")
  @ResponseStatus(HttpStatus.NO_CONTENT)
  public void deleteIngredient(@PathVariable Long id, @PathVariable long ingredientId,
      Authentication auth) {
    //noinspection ResultOfMethodCallIgnored
    userService.get(auth)
        .flatMap((user) ->
            mealRepository.findById(id)
                .map((meal) -> {
                  userService.requireAccess(user, meal.getCreator());
                  return meal;
                })
        )
        .flatMap((meal) ->
            ingredientRepository.findById(ingredientId)
                .map((existing) -> {
                  ingredientRepository.delete(existing);
                  return null;
                })
        )
        .orElse(null);
  }

  /**
   * Allows the user to delete a Meal they have created
   *
   * @param id - ID associated with the specific meal they would like to delete
   */
  // TODO set Calendar meal slots containing deleted meal to null
  @DeleteMapping(value = "/{id:\\d+}")
  @ResponseStatus(HttpStatus.NO_CONTENT)
  public void delete(@PathVariable Long id, Authentication auth) {
    mealRepository.delete(get(id, auth));
  }

}
